Repository jenkinsci/azure-vm-agents-plugin, pull requests merged in 2021-04, with the labels that each got.

#261 Sort regions and update azure-commons
  pom.xml
  src/main/java/com/microsoft/azure/vmagent/AzureVMAgentTemplate.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMCloud.java
  src/main/java/com/microsoft/azure/vmagent/util/AzureClientUtil.java
Labels: bug

#262 Provide adminPassword as a secret parameter
  src/main/java/com/microsoft/azure/vmagent/AzureVMManagementServiceDelegate.java
  src/main/resources/customImageTemplate.json
  src/main/resources/customImageTemplateWithManagedDisk.json
  src/main/resources/customImageTemplateWithScript.json
  src/main/resources/customImageTemplateWithScriptAndManagedDisk.json
  src/main/resources/referenceImageIDTemplateWithManagedDisk.json
  src/main/resources/referenceImageIDTemplateWithScriptAndManagedDisk.json
  src/main/resources/referenceImageTemplate.json
  src/main/resources/referenceImageTemplateWithManagedDisk.json
  src/main/resources/referenceImageTemplateWithScript.json
  src/main/resources/referenceImageTemplateWithScriptAndManagedDisk.json
Labels: bug

#263 Support SSD / premium SSD managed disks
  pom.xml
  src/main/java/com/microsoft/azure/vmagent/AzureVMAgentTemplate.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMManagementServiceDelegate.java
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgentTemplate/config.jelly
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgentTemplate/config.properties
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgentTemplate/help-osDiskStorageAccountType.html
  src/main/resources/customImageTemplateWithManagedDisk.json
  src/main/resources/customImageTemplateWithScriptAndManagedDisk.json
  src/main/resources/referenceImageIDTemplateWithManagedDisk.json
  src/main/resources/referenceImageIDTemplateWithScriptAndManagedDisk.json
  src/main/resources/referenceImageTemplateWithManagedDisk.json
  src/main/resources/referenceImageTemplateWithScriptAndManagedDisk.json
  src/main/webapp/help-storageAccountType.html
  src/test/java/com/microsoft/azure/vmagent/test/ITAzureVMManagementServiceDelegate.java
Labels: enhancement

#264 Support for spot instances
  src/main/java/com/microsoft/azure/vmagent/AzureVMAgentTemplate.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMManagementServiceDelegate.java
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgentTemplate/config.jelly
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgentTemplate/help-spotInstance.html
Labels: enhancement

#265 Support user and system assigned identity at the same time
  src/main/java/com/microsoft/azure/vmagent/AzureVMAgentTemplate.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMManagementServiceDelegate.java
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgentTemplate/config.jelly
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgentTemplate/config.properties
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgentTemplate/help-enableMSI.html
Labels: bug

#270 Disable windows build
  Jenkinsfile
Labels: chore

#269 Remove adminPassword that does nothing
  src/main/java/com/microsoft/azure/vmagent/AzureVMManagementServiceDelegate.java
Labels: bug

#271 Add option for limiting the number of VMs deployed in parallel
  src/main/java/com/microsoft/azure/vmagent/AzureVMAgentTemplate.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMMaintainPoolTask.java
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgentTemplate/config.jelly
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgentTemplate/config.properties
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgentTemplate/help-maximumDeploymentSize.html
Labels: enhancement

#272 Allow limiting of the deployment size when using "Azure VM Idle Retention Strategy"
  src/main/java/com/microsoft/azure/vmagent/AzureVMCloud.java
Labels: bug
