Repository jenkinsci/azure-vm-agents-plugin, pull requests merged in 2021-03, with the labels that each got.

#187 Fix NullPointerException after restart of Jenkins controller when agent resumes from suspend
  src/main/java/com/microsoft/azure/vmagent/AzureVMCloud.java
Labels: bug

#253 Enable automatic release on merge to master
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .mvn/extensions.xml
  .mvn/maven.config
  checkstyle.xml
  pom.xml
  src/main/java/com/microsoft/azure/vmagent/builders/AdvancedImageFluent.java
  src/main/resources/com/microsoft/azure/vmagent/Messages.properties
Labels: chore

#254 Use https for accessing storage accounts
  src/main/resources/customImageTemplate.json
  src/main/resources/customImageTemplateWithScript.json
  src/main/resources/referenceImageIDTemplateWithManagedDisk.json
  src/main/resources/referenceImageIDTemplateWithScriptAndManagedDisk.json
  src/main/resources/referenceImageTemplate.json
  src/main/resources/referenceImageTemplateWithManagedDisk.json
  src/main/resources/referenceImageTemplateWithScript.json
  src/main/resources/referenceImageTemplateWithScriptAndManagedDisk.json
Labels: bug

#255 Make git download script more robust
  src/main/resources/scripts/windowsInstallGitScript.ps1
Labels: enhancement

#258 Archive changelog
  CHANGELOG-old.md
Labels: chore

#260 Update builtin images, add Ubuntu 20.04, Windows Server 2019
  docs/init-scripts/windows-inbound-agent.ps1
  docs/init-scripts/windows-ssh.ps1
  src/main/java/com/microsoft/azure/vmagent/AzureVMAgentTemplate.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMManagementServiceDelegate.java
  src/main/java/com/microsoft/azure/vmagent/util/Constants.java
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgent/configure-entries.jelly
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgentTemplate/config.jelly
  src/main/resources/scripts/init.ps1
  src/main/resources/scripts/ubuntuInstallDockerScript.sh
  src/main/resources/scripts/ubuntuInstallGitScript.sh
  src/main/resources/scripts/ubuntuInstallJavaScript.sh
  src/main/resources/scripts/ubuntuInstallMavenScript.sh
  src/main/resources/scripts/windowsInstallGitScript.ps1
  src/main/resources/scripts/windowsInstallJavaScript.ps1
  src/main/resources/scripts/windowsInstallJnlpScript.ps1
  src/main/resources/scripts/windowsInstallMavenScript.ps1
  src/main/webapp/help-initScript.html
Labels: feature
