Repository jenkinsci/azure-vm-agents-plugin, pull requests merged in 2022-06, with the labels that each got.

#360 Revert "Reconnect offline agents"
  src/main/java/com/microsoft/azure/vmagent/AzureVMCloudOnceRetentionStrategy.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMCloudPoolRetentionStrategy.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMCloudRetensionStrategy.java
  src/main/resources/scripts/ubuntuInstallMavenScript.sh
  src/main/webapp/help-initScript.html
Labels: bug

#366 chore: use jenkins infra maven cd reusable workflow
  .github/workflows/cd.yaml
Labels: chore

#368 Update maven
  src/main/resources/scripts/ubuntuInstallMavenScript.sh
Labels: enhancement

#367 When limiting VMs per template, count template VMs not all cloud VMs
  .gitignore
  src/main/java/com/microsoft/azure/vmagent/AzureVMAgent.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMCloud.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMCloudVerificationTask.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMManagementServiceDelegate.java
  src/test/java/com/microsoft/azure/vmagent/AzureClientUtil.java
  src/test/java/com/microsoft/azure/vmagent/AzureVMCloudTest.java
  src/test/java/com/microsoft/azure/vmagent/ITAzureVMAgentCleanUpTask.java
  src/test/java/com/microsoft/azure/vmagent/ITAzureVMCloud.java
  src/test/java/com/microsoft/azure/vmagent/ITAzureVMManagementServiceDelegate.java
  src/test/java/com/microsoft/azure/vmagent/IntegrationTest.java
  src/test/java/com/microsoft/azure/vmagent/TestDeploymentTag.java
Labels: bug
