Repository jenkinsci/azure-vm-agents-plugin, pull requests merged in 2023-04, with the labels that each got.

#404 Cleanup pom
  pom.xml
Labels: chore

#405 Remove NIC and IP address on deletion using Azure built-in functionality
  src/main/java/com/microsoft/azure/vmagent/AzureVMManagementServiceDelegate.java
  src/main/resources/customImageTemplate.json
  src/main/resources/customImageTemplateWithManagedDisk.json
  src/main/resources/customImageTemplateWithScript.json
  src/main/resources/customImageTemplateWithScriptAndManagedDisk.json
  src/main/resources/referenceImageIDTemplateWithManagedDisk.json
  src/main/resources/referenceImageIDTemplateWithScriptAndManagedDisk.json
  src/main/resources/referenceImageTemplate.json
  src/main/resources/referenceImageTemplateWithManagedDisk.json
  src/main/resources/referenceImageTemplateWithScript.json
  src/main/resources/referenceImageTemplateWithScriptAndManagedDisk.json
  src/test/java/com/microsoft/azure/vmagent/ITAzureVMManagementServiceDelegate.java
Labels: enhancement

#357 Support SSH Config in template configuration
  src/main/java/com/microsoft/azure/vmagent/AzureVMAgent.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMAgentTemplate.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMManagementServiceDelegate.java
  src/main/java/com/microsoft/azure/vmagent/builders/AdvancedImage.java
  src/main/java/com/microsoft/azure/vmagent/builders/AdvancedImageBuilder.java
  src/main/java/com/microsoft/azure/vmagent/builders/AdvancedImageFluent.java
  src/main/java/com/microsoft/azure/vmagent/builders/AzureVMTemplateBuilder.java
  src/main/java/com/microsoft/azure/vmagent/remote/AzureVMAgentSSHLauncher.java
  src/main/java/com/microsoft/azure/vmagent/util/TemplateUtil.java
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgentTemplate/config.jelly
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgentTemplate/config.properties
  src/main/resources/com/microsoft/azure/vmagent/Messages.properties
  src/main/webapp/help-sshConfig.html
  src/test/java/com/microsoft/azure/vmagent/test/datamigration/AzureVMAgentTemplateReadResolveTest.java
  src/test/resources/com/microsoft/azure/vmagent/test/datamigration/AzureVMAgentTemplateReadResolveTest/config.xml
Labels: enhancement

#406 Linux inbound agent support
  README.md
  docs/init-scripts/linux-inbound-agent.sh
  docs/init-scripts/windows-inbound-agent.ps1
  src/main/java/com/microsoft/azure/vmagent/AzureVMAgentTemplate.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMCloud.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMCloudVerificationTask.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMManagementServiceDelegate.java
  src/main/java/com/microsoft/azure/vmagent/util/AzureUtil.java
  src/main/java/com/microsoft/azure/vmagent/util/Constants.java
  src/main/resources/com/microsoft/azure/vmagent/Messages.properties
  src/main/resources/customImageTemplateWithScript.json
  src/main/resources/customImageTemplateWithScriptAndManagedDisk.json
  src/main/resources/referenceImageIDTemplateWithScriptAndManagedDisk.json
  src/main/resources/referenceImageTemplateWithScript.json
  src/main/resources/referenceImageTemplateWithScriptAndManagedDisk.json
  src/main/resources/scripts/init.ps1
  src/main/resources/scripts/ubuntuInstallMavenScript.sh
  src/main/webapp/help-initScript.html
Labels: enhancement

#411 UI Improvements
  pom.xml
  src/main/java/com/microsoft/azure/vmagent/AzureVMAgentCleanUpTask.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMAgentTemplate.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMManagementServiceDelegate.java
  src/main/java/com/microsoft/azure/vmagent/builders/AzureVMTemplateBuilder.java
  src/main/java/com/microsoft/azure/vmagent/launcher/AzureComputerLauncher.java
  src/main/java/com/microsoft/azure/vmagent/launcher/AzureInboundLauncher.java
  src/main/java/com/microsoft/azure/vmagent/launcher/AzureSSHLauncher.java
  src/main/java/com/microsoft/azure/vmagent/util/TemplateUtil.java
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgentTemplate/config.jelly
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgentTemplate/config.properties
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgentTemplate/help-launcher.html
  src/main/resources/com/microsoft/azure/vmagent/AzureVMCloud/config.jelly
  src/main/resources/com/microsoft/azure/vmagent/AzureVMCloud/config.properties
  src/main/resources/com/microsoft/azure/vmagent/AzureVMComputer/configure.jelly
  src/main/resources/com/microsoft/azure/vmagent/AzureVMComputer/configure.properties
  src/main/resources/com/microsoft/azure/vmagent/Messages.properties
  src/main/resources/com/microsoft/azure/vmagent/launcher/AzureSSHLauncher/config.jelly
  src/main/resources/com/microsoft/azure/vmagent/launcher/AzureSSHLauncher/config.properties
  src/main/webapp/help-agentLaunchMethod.html
  src/test/java/com/microsoft/azure/vmagent/ITAzureVMCloud.java
  src/test/java/com/microsoft/azure/vmagent/IntegrationTest.java
  src/test/java/com/microsoft/azure/vmagent/test/jcasc/AdvancedConfigAsCodeTest.java
  src/test/java/com/microsoft/azure/vmagent/test/jcasc/BasicConfigAsCodeTest.java
  src/test/resources/com/microsoft/azure/vmagent/test/jcasc/advanced.yaml
  src/test/resources/com/microsoft/azure/vmagent/test/jcasc/basic.yaml
  src/test/resources/com/microsoft/azure/vmagent/test/jcasc/expectedAdvanced.yaml
  src/test/resources/com/microsoft/azure/vmagent/test/jcasc/expectedBasic.yaml
Labels: breaking
