Repository jenkinsci/azure-vm-agents-plugin, pull requests merged in 2023-03, with the labels that each got.

#382 Refresh plugin for 2023
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/renovate.json
  .mvn/extensions.xml
  Jenkinsfile
  pom.xml
  src/main/java/com/microsoft/azure/vmagent/AzureVMAgentCleanUpTask.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMAgentTemplate.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMCloud.java
  src/spotbugs/excludesFilter.xml
Labels: developer

#381 Don't attempt to delete public IP address resource when using private IP
  .gitignore
  src/main/java/com/microsoft/azure/vmagent/AzureVMCloud.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMManagementServiceDelegate.java
  src/test/java/com/microsoft/azure/vmagent/ITAzureVMManagementServiceDelegate.java
Labels: bug

#392 Switch to renovate
  .github/renovate.json
Labels: chore
