Repository jenkinsci/azure-vm-agents-plugin, pull requests merged in 2023-09, with the labels that each got.

#452 Supply purchase plan for gallery images
  src/main/java/com/microsoft/azure/vmagent/AzureVMManagementServiceDelegate.java
Labels: bug

#457 remove redundant cloudName
  src/main/java/com/microsoft/azure/vmagent/AzureVMCloud.java
Labels: developer

#462 [JENKINS-71737] rename cloudName to name
  pom.xml
  src/main/java/com/microsoft/azure/vmagent/AzureVMCloud.java
  src/main/resources/com/microsoft/azure/vmagent/AzureVMCloud/config.jelly
  src/test/resources/com/microsoft/azure/vmagent/test/jcasc/advanced.yaml
  src/test/resources/com/microsoft/azure/vmagent/test/jcasc/basic.yaml
  src/test/resources/com/microsoft/azure/vmagent/test/jcasc/expectedAdvanced.yaml
  src/test/resources/com/microsoft/azure/vmagent/test/jcasc/expectedBasic.yaml
Labels: breaking
