Repository jenkinsci/azure-vm-agents-plugin, pull requests merged in 2024-11, with the labels that each got.

#576 Make premium OS disk option available to any type
  src/main/java/com/microsoft/azure/vmagent/AzureVMAgentTemplate.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMManagementServiceDelegate.java
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgentTemplate/help-osDiskStorageAccountType.html
Labels: enhancement

#570 Add support for node properties to template
  src/main/java/com/microsoft/azure/vmagent/AzureVMAgent.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMAgentTemplate.java
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgentTemplate/config.jelly
  src/main/resources/com/microsoft/azure/vmagent/AzureVMComputer/configure.jelly
  src/test/java/com/microsoft/azure/vmagent/test/jcasc/BasicConfigAsCodeTest.java
  src/test/resources/com/microsoft/azure/vmagent/test/jcasc/basic.yaml
  src/test/resources/com/microsoft/azure/vmagent/test/jcasc/expectedBasic.yaml
Labels: enhancement

#586 Migrate availability type to use descriptor
  src/main/java/com/microsoft/azure/vmagent/AzureVMAgentTemplate.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMManagementServiceDelegate.java
  src/main/java/com/microsoft/azure/vmagent/availability/AvailabilitySet.java
  src/main/java/com/microsoft/azure/vmagent/availability/AzureAvailabilityType.java
  src/main/java/com/microsoft/azure/vmagent/availability/NoAvailabilityRequired.java
  src/main/java/com/microsoft/azure/vmagent/builders/Availability.java
  src/main/java/com/microsoft/azure/vmagent/builders/AvailabilityBuilder.java
  src/main/java/com/microsoft/azure/vmagent/builders/AzureVMTemplateBuilder.java
  src/main/java/com/microsoft/azure/vmagent/builders/AzureVMTemplateFluent.java
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgentTemplate/config.jelly
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgentTemplate/config.properties
  src/main/resources/com/microsoft/azure/vmagent/AzureVMAgentTemplate/help-availabilityType.html
  src/main/resources/com/microsoft/azure/vmagent/Messages.properties
  src/main/resources/com/microsoft/azure/vmagent/availability/AvailabilitySet/config.jelly
  src/test/java/com/microsoft/azure/vmagent/IntegrationTest.java
  src/test/java/com/microsoft/azure/vmagent/test/datamigration/AzureVMAgentTemplateReadResolveTest.java
  src/test/resources/com/microsoft/azure/vmagent/test/jcasc/advanced.yaml
  src/test/resources/com/microsoft/azure/vmagent/test/jcasc/expectedAdvanced.yaml
  src/test/resources/com/microsoft/azure/vmagent/test/jcasc/expectedBasic.yaml
Labels: developer

#589 Handle SSH launcher not being exported by JCasC
  src/main/java/com/microsoft/azure/vmagent/AzureVMAgent.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMAgentTemplate.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMManagementServiceDelegate.java
Labels: bug

#591 Allow copying existing agent template
  src/main/java/com/microsoft/azure/vmagent/AzureVMAgentTemplate.java
  src/main/java/com/microsoft/azure/vmagent/AzureVMCloud.java
  src/main/resources/com/microsoft/azure/vmagent/AzureVMCloud/_new.jelly
  src/main/resources/com/microsoft/azure/vmagent/AzureVMCloud/new.jelly
  src/main/resources/com/microsoft/azure/vmagent/Messages.properties
Labels: enhancement
