Repository jenkinsci/azure-vm-agents-plugin, pull requests merged in 2025-03, with the labels that each got.

#644 Migrate tests to JUnit5
  src/test/java/com/microsoft/azure/vmagent/AzureVMCloudTest.java
  src/test/java/com/microsoft/azure/vmagent/ITAzureVMAgentCleanUpTask.java
  src/test/java/com/microsoft/azure/vmagent/ITAzureVMCloud.java
  src/test/java/com/microsoft/azure/vmagent/ITAzureVMManagementServiceDelegate.java
  src/test/java/com/microsoft/azure/vmagent/IntegrationTest.java
  src/test/java/com/microsoft/azure/vmagent/TestDeploymentTag.java
  src/test/java/com/microsoft/azure/vmagent/test/datamigration/AzureVMAgentTemplateReadResolveTest.java
  src/test/java/com/microsoft/azure/vmagent/test/jcasc/AdvancedConfigAsCodeTest.java
  src/test/java/com/microsoft/azure/vmagent/test/jcasc/BasicConfigAsCodeTest.java
  src/test/java/com/microsoft/azure/vmagent/util/KeyDecoderTest.java
Labels: test

#646 Switching from using legacyInstanceId to the Jenkins controller URL for the jenkinsResourceTag value
  .gitignore
  src/main/java/com/microsoft/azure/vmagent/util/AzureUtil.java
  src/test/java/com/microsoft/azure/vmagent/TestDeploymentTag.java
Labels: enhancement

#647 Migrate to EE 9 in Jelly view
  src/main/resources/com/microsoft/azure/vmagent/AzureVMCloud/templates.jelly
Labels: internal
